In [1]:
import pandas as pd

In [2]:
movie = pd.read_csv('./tmdb_5000_movies.csv')
credit = pd.read_csv('./tmdb_5000_credits.csv')

In [6]:
data = pd.concat([movie, credit], axis=1, join="inner")

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
 20  movie_id              4803 non-null   int64
 21  title                 4803 non-null   object
 22  cast                  4803 non-null   object
 23  crew                  4803 non-null   object
dtypes: float64(3), int64(5), object(16)
memory usage: 900.7+ KB

In [18]:
listdata["genres"][0]

['[',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 ' ',
 '2',
 '8',
 ',',
 ' ',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 ' ',
 '"',
 'A',
 'c',
 't',
 'i',
 'o',
 'n',
 '"',
 '}',
 ',',
 ' ',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 ' ',
 '1',
 '2',
 ',',
 ' ',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 ' ',
 '"',
 'A',
 'd',
 'v',
 'e',
 'n',
 't',
 'u',
 'r',
 'e',
 '"',
 '}',
 ',',
 ' ',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 ' ',
 '1',
 '4',
 ',',
 ' ',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 ' ',
 '"',
 'F',
 'a',
 'n',
 't',
 'a',
 's',
 'y',
 '"',
 '}',
 ',',
 ' ',
 '{',
 '"',
 'i',
 'd',
 '"',
 ':',
 ' ',
 '8',
 '7',
 '8',
 ',',
 ' ',
 '"',
 'n',
 'a',
 'm',
 'e',
 '"',
 ':',
 ' ',
 '"',
 'S',
 'c',
 'i',
 'e',
 'n',
 'c',
 'e',
 ' ',
 'F',
 'i',
 'c',
 't',
 'i',
 'o',
 'n',
 '"',
 '}',
 ']']